version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build: 
      context: ./Server
      # This is your react-client host address
      args:
        HOST: http://localhost:3000
        REDIRECT-HOST: http://localhost:8080

    ports:
      - "8080:8080"
    environment:
      - MONGODB_HOST=mongodb://mongodb:27017/
    depends_on:
      - mongodb



  client:
    build: 
      context: ./client
      args:
      # This is your go backend host address
        REACT_APP_API_URL: http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
